source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!


def pod_afnetworking
    pod 'Alamofire', '~> 3.2.1'
end

target 'MetroTransit' do
    pod_afnetworking

end

target 'MetroTransitTests' do
    pod_afnetworking
    pod 'OHHTTPStubs'
    pod 'OHHTTPStubs/Swift'
end

